### PR TITLE
Page 1 MVC

### PR DESCRIPTION
**Pull request by filipbrej**
Refactored Page 1 to follow MVC design pattern.

### CODE REVIEW

**Comment by white0ut** [comment]
Hey Fil,

How did you create this PR? It looks like you took your workspace and zipped it up, then uploaded it.

Git is a distributed version control system. So you don't have to zip anything up. You actually apply your changes locally and add the changes. Git tracks those changes and displays a character-by-character diff of everything that has changed for every file changed, anytime any developer adds or deletes code.

You should be able to just make your changes, view the diff of the changes you've made, and if they look good - put them into a commit.

Once you have enough commits to encapsulate some chunk of work, you can create a Pull Request to merge all of those commits in a branch into master.


Does that make sense?

**Comment by white0ut** [comment]
I went ahead and unzipped your file and applied it to a branch on my fork of the repo, check it out here: https://github.com/white0ut/chd-ios/commit/b72e67767859f8e1b33dee92788beaa7b2d6a151

It isn't clear to me what changes you've made. What changes did you intend to make? Were they maybe not attached?

**Comment by filipbrej** [comment]
Thanks for the breakdown of how git works, I'll be sure to keep it in mind for the future.

Just checked your fork. That's bizarre. I didn't manually zip anything, I just uploaded the file through github and noticed that it was a zip when it was done. I opened it and it's not what I wanted to upload at all. I'll try again tomorrow morning (again still new to collaboration through git/github, hopefully it goes right this time).

**Comment by white0ut** [comment]
I'd suggest using either the GitHub app or the command line. Git is
complicated, but the more you use it and learn, you'll never want to live
without it. It the bee's knees!

Stick with it! Break all the things!

**Pull request closed without merging**
